import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "bg-red-50",
    "bg-red-100",
    "bg-red-500",
    "bg-orange-50",
    "bg-orange-100",
    "bg-orange-500",
    "bg-amber-50",
    "bg-amber-100",
    "bg-amber-500",
    "bg-yellow-50",
    "bg-yellow-100",
    "bg-yellow-500",
    "bg-lime-50",
    "bg-lime-100",
    "bg-lime-500",
    "bg-green-50",
    "bg-green-100",
    "bg-green-500",
    "bg-emerald-50",
    "bg-emerald-100",
    "bg-emerald-500",
    "bg-teal-50",
    "bg-teal-100",
    "bg-teal-500",
    "bg-cyan-50",
    "bg-cyan-100",
    "bg-cyan-500",
    "bg-sky-50",
    "bg-sky-100",
    "bg-sky-500",
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-500",
    "bg-indigo-50",
    "bg-indigo-100",
    "bg-indigo-500",
    "bg-violet-50",
    "bg-violet-100",
    "bg-violet-500",
    "bg-purple-50",
    "bg-purple-100",
    "bg-purple-500",
    "bg-fuchsia-50",
    "bg-fuchsia-100",
    "bg-fuchsia-500",
    "bg-pink-50",
    "bg-pink-100",
    "bg-pink-500",
    "bg-rose-50",
    "bg-rose-100",
    "bg-rose-500",
    "bg-gray-50",
    "bg-gray-100",
    "bg-gray-500",
    "bg-slate-50",
    "bg-slate-100",
    "bg-slate-500",
    "bg-zinc-50",
    "bg-zinc-100",
    "bg-zinc-500",
    "bg-neutral-50",
    "bg-neutral-100",
    "bg-neutral-500",
    "bg-stone-50",
    "bg-stone-100",
    "bg-stone-500",

    "border-red-50",
    "border-red-500",
    "border-orange-50",
    "border-orange-500",
    "border-amber-50",
    "border-amber-500",
    "border-yellow-50",
    "border-yellow-500",
    "border-lime-50",
    "border-lime-500",
    "border-green-50",
    "border-green-500",
    "border-emerald-50",
    "border-emerald-500",
    "border-teal-50",
    "border-teal-500",
    "border-cyan-50",
    "border-cyan-500",
    "border-sky-50",
    "border-sky-500",
    "border-blue-50",
    "border-blue-500",
    "border-indigo-50",
    "border-indigo-500",
    "border-violet-50",
    "border-violet-500",
    "border-purple-50",
    "border-purple-500",
    "border-fuchsia-50",
    "border-fuchsia-500",
    "border-pink-50",
    "border-pink-500",
    "border-rose-50",
    "border-rose-500",
    "border-gray-50",
    "border-gray-500",
    "border-slate-50",
    "border-slate-500",
    "border-zinc-50",
    "border-zinc-500",
    "border-neutral-50",
    "border-neutral-500",
    "border-stone-50",
    "border-stone-500",

    "text-red-50",
    "text-red-100",
    "text-red-500",
    "text-orange-50",
    "text-orange-100",
    "text-orange-500",
    "text-amber-50",
    "text-amber-100",
    "text-amber-500",
    "text-yellow-50",
    "text-yellow-100",
    "text-yellow-500",
    "text-lime-50",
    "text-lime-100",
    "text-lime-500",
    "text-green-50",
    "text-green-100",
    "text-green-500",
    "text-emerald-50",
    "text-emerald-100",
    "text-emerald-500",
    "text-teal-50",
    "text-teal-100",
    "text-teal-500",
    "text-cyan-50",
    "text-cyan-100",
    "text-cyan-500",
    "text-sky-50",
    "text-sky-100",
    "text-sky-500",
    "text-blue-50",
    "text-blue-100",
    "text-blue-500",
    "text-indigo-50",
    "text-indigo-100",
    "text-indigo-500",
    "text-violet-50",
    "text-violet-100",
    "text-violet-500",
    "text-purple-50",
    "text-purple-100",
    "text-purple-500",
    "text-fuchsia-50",
    "text-fuchsia-100",
    "text-fuchsia-500",
    "text-pink-50",
    "text-pink-100",
    "text-pink-500",
    "text-rose-50",
    "text-rose-100",
    "text-rose-500",
    "text-gray-50",
    "text-gray-100",
    "text-gray-500",
    "text-slate-50",
    "text-slate-100",
    "text-slate-500",
    "text-zinc-50",
    "text-zinc-100",
    "text-zinc-500",
    "text-neutral-50",
    "text-neutral-100",
    "text-neutral-500",
    "text-stone-50",
    "text-stone-100",
    "text-stone-500",

    "dark:bg-red-50",
    "dark:bg-red-100",
    "dark:bg-red-500",
    "dark:bg-orange-50",
    "dark:bg-orange-100",
    "dark:bg-orange-500",
    "dark:bg-amber-50",
    "dark:bg-amber-100",
    "dark:bg-amber-500",
    "dark:bg-yellow-50",
    "dark:bg-yellow-100",
    "dark:bg-yellow-500",
    "dark:bg-lime-50",
    "dark:bg-lime-100",
    "dark:bg-lime-500",
    "dark:bg-green-50",
    "dark:bg-green-100",
    "dark:bg-green-500",
    "dark:bg-emerald-50",
    "dark:bg-emerald-100",
    "dark:bg-emerald-500",
    "dark:bg-teal-50",
    "dark:bg-teal-100",
    "dark:bg-teal-500",
    "dark:bg-cyan-50",
    "dark:bg-cyan-100",
    "dark:bg-cyan-500",
    "dark:bg-sky-50",
    "dark:bg-sky-100",
    "dark:bg-sky-500",
    "dark:bg-blue-50",
    "dark:bg-blue-100",
    "dark:bg-blue-500",
    "dark:bg-indigo-50",
    "dark:bg-indigo-100",
    "dark:bg-indigo-500",
    "dark:bg-violet-50",
    "dark:bg-violet-100",
    "dark:bg-violet-500",
    "dark:bg-purple-50",
    "dark:bg-purple-100",
    "dark:bg-purple-500",
    "dark:bg-fuchsia-50",
    "dark:bg-fuchsia-100",
    "dark:bg-fuchsia-500",
    "dark:bg-pink-50",
    "dark:bg-pink-100",
    "dark:bg-pink-500",
    "dark:bg-rose-50",
    "dark:bg-rose-100",
    "dark:bg-rose-500",
    "dark:bg-gray-50",
    "dark:bg-gray-100",
    "dark:bg-gray-500",
    "dark:bg-slate-50",
    "dark:bg-slate-100",
    "dark:bg-slate-500",
    "dark:bg-zinc-50",
    "dark:bg-zinc-100",
    "dark:bg-zinc-500",
    "dark:bg-neutral-50",
    "dark:bg-neutral-100",
    "dark:bg-neutral-500",
    "dark:bg-stone-50",
    "dark:bg-stone-100",
    "dark:bg-stone-500",

    "dark:border-red-50",
    "dark:border-red-500",
    "dark:border-orange-50",
    "dark:border-orange-500",
    "dark:border-amber-50",
    "dark:border-amber-500",
    "dark:border-yellow-50",
    "dark:border-yellow-500",
    "dark:border-lime-50",
    "dark:border-lime-500",
    "dark:border-green-50",
    "dark:border-green-500",
    "dark:border-emerald-50",
    "dark:border-emerald-500",
    "dark:border-teal-50",
    "dark:border-teal-500",
    "dark:border-cyan-50",
    "dark:border-cyan-500",
    "dark:border-sky-50",
    "dark:border-sky-500",
    "dark:border-blue-50",
    "dark:border-blue-500",
    "dark:border-indigo-50",
    "dark:border-indigo-500",
    "dark:border-violet-50",
    "dark:border-violet-500",
    "dark:border-purple-50",
    "dark:border-purple-500",
    "dark:border-fuchsia-50",
    "dark:border-fuchsia-500",
    "dark:border-pink-50",
    "dark:border-pink-500",
    "dark:border-rose-50",
    "dark:border-rose-500",
    "dark:border-gray-50",
    "dark:border-gray-500",
    "dark:border-slate-50",
    "dark:border-slate-500",
    "dark:border-zinc-50",
    "dark:border-zinc-500",
    "dark:border-neutral-50",
    "dark:border-neutral-500",
    "dark:border-stone-50",
    "dark:border-stone-500",

    "dark:text-red-50",
    "dark:text-red-100",
    "dark:text-red-500",
    "dark:text-orange-50",
    "dark:text-orange-100",
    "dark:text-orange-500",
    "dark:text-amber-50",
    "dark:text-amber-100",
    "dark:text-amber-500",
    "dark:text-yellow-50",
    "dark:text-yellow-100",
    "dark:text-yellow-500",
    "dark:text-lime-50",
    "dark:text-lime-100",
    "dark:text-lime-500",
    "dark:text-green-50",
    "dark:text-green-100",
    "dark:text-green-500",
    "dark:text-emerald-50",
    "dark:text-emerald-100",
    "dark:text-emerald-500",
    "dark:text-teal-50",
    "dark:text-teal-100",
    "dark:text-teal-500",
    "dark:text-cyan-50",
    "dark:text-cyan-100",
    "dark:text-cyan-500",
    "dark:text-sky-50",
    "dark:text-sky-100",
    "dark:text-sky-500",
    "dark:text-blue-50",
    "dark:text-blue-100",
    "dark:text-blue-500",
    "dark:text-indigo-50",
    "dark:text-indigo-100",
    "dark:text-indigo-500",
    "dark:text-violet-50",
    "dark:text-violet-100",
    "dark:text-violet-500",
    "dark:text-purple-50",
    "dark:text-purple-100",
    "dark:text-purple-500",
    "dark:text-fuchsia-50",
    "dark:text-fuchsia-100",
    "dark:text-fuchsia-500",
    "dark:text-pink-50",
    "dark:text-pink-100",
    "dark:text-pink-500",
    "dark:text-rose-50",
    "dark:text-rose-100",
    "dark:text-rose-500",
    "dark:text-gray-50",
    "dark:text-gray-100",
    "dark:text-gray-500",
    "dark:text-slate-50",
    "dark:text-slate-100",
    "dark:text-slate-500",
    "dark:text-zinc-50",
    "dark:text-zinc-100",
    "dark:text-zinc-500",
    "dark:text-neutral-50",
    "dark:text-neutral-100",
    "dark:text-neutral-500",
    "dark:text-stone-50",
    "dark:text-stone-100",
    "dark:text-stone-500",
  ],
  theme: {
  	extend: {
  		colors: {
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			popover: {
  				DEFAULT: 'hsl(var(--popover))',
  				foreground: 'hsl(var(--popover-foreground))'
  			},
  			primary: {
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			destructive: {
  				DEFAULT: 'hsl(var(--destructive))',
  				foreground: 'hsl(var(--destructive-foreground))'
  			},
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			chart: {
  				'1': 'hsl(var(--chart-1))',
  				'2': 'hsl(var(--chart-2))',
  				'3': 'hsl(var(--chart-3))',
  				'4': 'hsl(var(--chart-4))',
  				'5': 'hsl(var(--chart-5))'
  			}
  		},
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		},
  		keyframes: {
  			'accordion-down': {
  				from: {
  					height: '0'
  				},
  				to: {
  					height: 'var(--radix-accordion-content-height)'
  				}
  			},
  			'accordion-up': {
  				from: {
  					height: 'var(--radix-accordion-content-height)'
  				},
  				to: {
  					height: '0'
  				}
  			}
  		},
  		animation: {
  			'accordion-down': 'accordion-down 0.2s ease-out',
  			'accordion-up': 'accordion-up 0.2s ease-out'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
